### ISSUE TITLE
Change the output format of the importer function

### ISSUE THREAD

**Issue by DawidNiezgodka** [lnrd96/SpecItems#17]
The current output format (`String[]`) of the first importer function could be changed to facilitate future work with spec items.
There are the following problems with the `String[]` output:
1. The current implementation does not cover the commit information that will appear at the top of a text file.
2. The output structure is rigid, i.e., one always assumes that there will be the exact number of attributes. Consider a scenario when a new commit arrives as a text file containing only the information about the referenced item and what changed. Then, the complete item would have 8 attributes and the updated 3, which will break the pattern. 
Thus, I suggest the following format of the output of the function to entail the information:
```
class ProcessedDocument {

    Commit commit;
    List<Map<String, String> specItems

}
```
Each map in the output list contains information about populated fields, and null instead.

**Comment by lnrd96** [comment]
Hi. Since we updated the issues, no proposals to exact input output format are present anymore. Feel free to design as you like.
